name: Ejemplo Comunicación de Almacenamiento

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Crear archivo
        run: echo "Datos importantes" > datos.txt
      - name: Subir archivo a Google Cloud Storage
        run: gsutil cp datos.txt gs://mi-bucket/datos.txt
      - name: Obtener enlace de descarga
        run: echo "Enlace de descarga: https://storage.googleapis.com/mi-bucket/datos.txt" >> enlace.txt
        # Guarda el enlace de descarga en un archivo para que pueda ser accedido por otros trabajos

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Descargar archivo desde enlace
        run: wget -O datos.txt $(cat enlace.txt)
      - name: Leer archivo
        run: cat datos.txt
