name: Upload to Telegram

on:
  push:
    branches:
      - main

jobs:
  upload_to_telegram:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Upload to Telegram
        uses: appleboy/telegram-action@master
        with:
          token: ${{ secrets.7046470389:AAGujKQfAvtB9oeXogGWOJRlfNOSC8jsCOY }}
          message: |
            ## OrangeFox Recovery Build - Unofficial
            Build: fox_${{ github.event.inputs.MANIFEST_BRANCH }}
            Device: [Device Tree/Branch](${{ github.event.inputs.DEVICE_TREE }}/tree/${{ github.event.inputs.DEVICE_TREE_BRANCH }})
            Commit: Most recent [commit](${{ github.event.inputs.DEVICE_TREE }}/commit/${{ env.COMMIT_ID }}) during building.
            ## MD5SUM
            * ${{ env.MD5_IMG }} for IMG file.
            * ${{ env.MD5_RAMDISK }} for IMG file.
            * ${{ env.MD5_R-RAMDISK }} for IMG file.
            * ${{ env.MD5_ZIP }} for ZIP file.
            * ${{ env.MD5_TAR }} for TAR file.
