name: Share Results Workflow

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    # Defining outputs for job1
    outputs:
      workspace: ${{ runner.workspace }}
    steps:
      - name: Create directory
        run: mkdir -p $GITHUB_WORKSPACE/my_directory

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Use workspace from job1
        run: echo "Using workspace" # Here you can use the $WORKSPACE variable to access the workspace directory
        env:
          WORKSPACE: ${{needs.job1.outputs.workspace}}

      - name: Check
        run: ls $GITHUB_WORKSPACE
