name: Ejemplo Comunicación de Almacenamiento

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Crear archivo
        run: echo "Datos importantes" > datos.txt
      - name: Subir archivo a Gist
        uses: actions/upload-artifact@v2
        with:
          name: datos
          path: datos.txt

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Descargar archivo desde Gist
        uses: actions/download-artifact@v2
        with:
          name: datos
      - name: Leer archivo
        run: cat datos.txt
