name: Ejemplo Comunicación de Almacenamiento

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Crear archivo
        run: echo "Datos importantes" > datos.txt
      - name: Subir archivo a AWS S3
        run: aws s3 cp datos.txt s3://mi-bucket/datos.txt

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Descargar archivo desde AWS S3
        run: aws s3 cp s3://mi-bucket/datos.txt datos.txt
      - name: Leer archivo
        run: cat datos.txt
