name: Test Comment Creation

on:
  workflow_dispatch:

jobs:
  test-comment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Execute script
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const github = context.repo;
            const message = `
              ## OrangeFox Recovery Build - Unofficial
              Build: fox_11.0
              Device: [Device Tree/Branch](https://github.com/TDD788/A12s-DevTree/tree/DT-Builder)
              Commit: Most recent [commit](https://github.com/TDD788/A12s-DevTree/commit/c7079e6f48bd7dde6179269a94aed12c39ed4ccd) during building.
              ## MD5SUM
              *  for IMG file.
              *  for ZIP file.
            `;
            github.issues.createComment({ ...github, issue_number: context.issue.number, body: message });
