name: Upload to Telegram

on:
  workflow_dispatch:
    inputs:
      MANIFEST_BRANCH:
        description: 'OrangeFox Manifest Branch'
        required: true
        default: '12.1'
        type: choice
        options:
        - 12.1
        - 11.0
      DEVICE_TREE:
        description: 'OrangeFox Device Tree'
        required: true
        default: 'https://github.com/TDD788/A12s-DevTree'
      DEVICE_TREE_BRANCH:
        description: 'OrangeFox Device Tree Branch'
        required: true
        default: 'DT-Builder'
      DEVICE_PATH:
        description: 'Specify your Device Path'
        required: true
        default: 'device/samsung/a12s'
      DEVICE_NAME:
        description: 'Specify your Device Codename'
        required: true
        default: 'a12s'
      RELEASE_TYPE:
        description: 'Release type'
        required: true
        type: choice
        options:
          - oficial
          - experimental
      BUILD_TARGET:
        description: 'Specify your Build Target'
        required: true
        default: 'recovery'
        type: choice
        options:
        - boot
        - recovery
        - vendorboot
        - you_mom

jobs:
  upload_to_telegram:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Upload to Telegram
        uses: appleboy/telegram-upload-file@v1
        with:
          host: api.telegram.org
          token: "7046470389:AAGujKQfAvtB9oeXogGWOJRlfNOSC8jsCOY"
          chat_id: -1001643052289
          caption: |
            ## OrangeFox Recovery Build - Unofficial
            Build: fox_${{ github.event.inputs.MANIFEST_BRANCH }}
            Device: [Device Tree/Branch](${{ github.event.inputs.DEVICE_TREE }}/tree/${{ github.event.inputs.DEVICE_TREE_BRANCH }})
            Commit: Most recent [commit](${{ github.event.inputs.DEVICE_TREE }}/commit/${{ env.COMMIT_ID }}) during building.
            ## MD5SUM
            * ${{ env.MD5_IMG }} for IMG file.
            * ${{ env.MD5_RAMDISK }} for IMG file.
            * ${{ env.MD5_R-RAMDISK }} for IMG file.
            * ${{ env.MD5_ZIP }} for ZIP file.
            * ${{ env.MD5_TAR }} for TAR file.
