name: Ejemplo Comunicación de Almacenamiento

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Crear archivo
        run: echo "Datos importantes" > datos.txt
      - name: Subir archivo a GitHub Releases
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: datos.txt
          asset_name: datos.txt
          asset_content_type: text/plain

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Descargar archivo desde GitHub Releases
        uses: actions/download-artifact@v2
        with:
          name: datos.txt
          path: .
      - name: Leer archivo
        run: cat datos.txt
