jobs:
  produce-results:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.generate-output.outputs.result }}
    steps:
      - name: Generate output
        id: generate-output
        run: |
          # Genera los archivos o resultados deseados
          echo "Hello, World!" > output.txt
          echo "::set-output name=result::output.txt"
    # Define el Github Workspace como el resultado de este job
    outputs:
      Github_Workspace: ${{ github.workspace }}

  consume-results:
    needs: produce-results
    runs-on: ubuntu-latest
    steps:
      - name: Use output from previous job
        run: |
          # Usa los archivos generados por el job anterior desde el Github Workspace
          cat ${{ needs.produce-results.outputs.result }}
          echo "The workspace is located at: ${{ needs.produce-results.outputs.Github_Workspace }}"
